### ISSUE TITLE
Problem running the bot 

### ISSUE THREAD

**Issue by MauricioAHM** [lucadentella/HomeAutomationBOT#1]
Hello, I was wondering if you could help me to solve this problem, when I try to run te bot it doesn't work and I have the next message 

Thank you.

module.js:338
    throw err;
          ^
Error: Cannot find module 'node-dht-sensor'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/Desktop/telegram/HomeAutomationBOT/bot.js:7:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by lucadentella** [comment]
Hi, you have to install the required node.js module... please follow the instruction in my blog post:
http://www.lucadentella.it/en/2015/10/13/automazione-con-bot-telegram/
